networks:
  app-tie:
    driver: bridge

services:
  php:
    container_name: php-apache
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - app-tie
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    networks:
      - app-tie
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true